### ISSUE TITLE
Ordering tokens

### ISSUE THREAD

**Issue by shinsyotta** [olehmisar/aztec-amm#5]
Not sure if I correctly understand what ordering tokens means, but it appears to me that test 4 in src/contracts/tokens-ordering/src/lib.nr is incorrect. It seems there should be an "!" before the test because token B has a larger address number than token A.

**Comment by olehmisar** [comment]
Good catch. I will blame it on Copilot.

**Comment by olehmisar** [comment]
It's fixed now. The only problem it could cause is incorrect initialisation of a pool. A pool is invalid if `token0.address > token1.address`.
